// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKl7XGXj3hn0jw_CPdeSK3NNtUDLgyL8',
    appId: '1:1044636784507:web:121e0b0835d054286dcfde',
    messagingSenderId: '1044636784507',
    projectId: 'masa-chat-sechack365-2024',
    authDomain: 'masa-chat-sechack365-2024.firebaseapp.com',
    storageBucket: 'masa-chat-sechack365-2024.appspot.com',
    measurementId: 'G-7Z87T4CD3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFtvU2nkOl8hR6lp6T31rZYzfMn2KH53o',
    appId: '1:1044636784507:android:fc879f408454aa556dcfde',
    messagingSenderId: '1044636784507',
    projectId: 'masa-chat-sechack365-2024',
    storageBucket: 'masa-chat-sechack365-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnRMNLCetApF-Q1a1XRbBjROT3gwcPQg',
    appId: '1:1044636784507:ios:8e3081cd99ea9e136dcfde',
    messagingSenderId: '1044636784507',
    projectId: 'masa-chat-sechack365-2024',
    storageBucket: 'masa-chat-sechack365-2024.appspot.com',
    iosBundleId: 'com.example.masaChatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmnRMNLCetApF-Q1a1XRbBjROT3gwcPQg',
    appId: '1:1044636784507:ios:8e3081cd99ea9e136dcfde',
    messagingSenderId: '1044636784507',
    projectId: 'masa-chat-sechack365-2024',
    storageBucket: 'masa-chat-sechack365-2024.appspot.com',
    iosBundleId: 'com.example.masaChatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcKl7XGXj3hn0jw_CPdeSK3NNtUDLgyL8',
    appId: '1:1044636784507:web:2cf7324d64a8db616dcfde',
    messagingSenderId: '1044636784507',
    projectId: 'masa-chat-sechack365-2024',
    authDomain: 'masa-chat-sechack365-2024.firebaseapp.com',
    storageBucket: 'masa-chat-sechack365-2024.appspot.com',
    measurementId: 'G-03CV0XKZ5Y',
  );
}
